import { nanoid } from "nanoid";
import { DESCRIPTOR, type Default, type ValueDescriptor, type ValueSpec } from "./descriptor";

type NullableOption<N extends boolean> = { nullable?: N };
type Nullable<T, N extends boolean> = N extends true ? T | null : T;

function value<T, P extends boolean>(
  property: P,
  spec: ValueSpec,
  defaultValue: Default<T>,
  nullable: boolean,
  isId = false
): ValueDescriptor<T, P> {
  return {
    [DESCRIPTOR]: "value",
    property,
    spec,
    nullable: nullable || defaultValue === null,
    isId,
    default: defaultValue
  };
}

function primitiveBuilders<P extends boolean>(property: P) {
  function string(defaultValue: null): ValueDescriptor<string | null, P>;
  function string<N extends boolean = false>(
    defaultValue: Default<string>,
    opt?: NullableOption<N>
  ): ValueDescriptor<Nullable<string, N>, P>;
  function string(defaultValue: Default<string> | null, opt?: NullableOption<boolean>) {
    return value(property, { type: "string" }, defaultValue, opt?.nullable === true);
  }

  function number(defaultValue: null): ValueDescriptor<number | null, P>;
  function number<N extends boolean = false>(
    defaultValue: Default<number>,
    opt?: NullableOption<N>
  ): ValueDescriptor<Nullable<number, N>, P>;
  function number(defaultValue: Default<number> | null, opt?: NullableOption<boolean>) {
    return value(property, { type: "number" }, defaultValue, opt?.nullable === true);
  }

  function boolean(defaultValue: null): ValueDescriptor<boolean | null, P>;
  function boolean<N extends boolean = false>(
    defaultValue: Default<boolean>,
    opt?: NullableOption<N>
  ): ValueDescriptor<Nullable<boolean, N>, P>;
  function boolean(defaultValue: Default<boolean> | null, opt?: NullableOption<boolean>) {
    return value(property, { type: "boolean" }, defaultValue, opt?.nullable === true);
  }

  /** String literal union. e.g. `enum(["start", "center", "end"], "start")` */
  function enumOf<const V extends readonly string[], N extends boolean = false>(
    values: V,
    defaultValue: Default<V[number]> | (N extends true ? null : never),
    opt?: NullableOption<N>
  ): ValueDescriptor<Nullable<V[number], N>, P> {
    return value(
      property,
      { type: "enum", values },
      defaultValue as Default<V[number]>,
      opt?.nullable === true
    );
  }

  return { string, number, boolean, enum: enumOf };
}

/** Regular ProjectData value that is not exposed to the Property system */
export const field = {
  ...primitiveBuilders(false),

  /** Record ID generated by nanoid */
  id(): ValueDescriptor<string, false> {
    return value(false, { type: "string" }, () => nanoid(), false, true);
  },

  /** Fixed value. e.g. `nodeType: field.literal("sequence")` */
  literal<const T extends string | number | boolean | null>(literal: T): ValueDescriptor<T, false> {
    return value(false, { type: "literal", value: literal }, literal, false);
  },

  /**
   * Serializable value without a declared structure (object, array, union, ...).
   * Always pass object/array defaults as functions to avoid sharing them between instances.
   */
  json<T>(defaultValue: Default<T>): ValueDescriptor<T, false> {
    return value(false, { type: "json" }, defaultValue, false);
  }
};

/** Value that other systems (Binding, Animation, Step, Plugin, ...) can reference and control */
export const prop = primitiveBuilders(true);
