import type { RecordKey } from "@shared/constants";
import type { RegisterOwned } from "@shared/projectData/factories/factory";
import type { RuntimeProjectData, Types } from "@shared/projectData/types";

type AnyRecord = Record<string, any>;

export type OwnedLog = { type: RecordKey; id: string; data: unknown }[];

const NANOID_PATTERN = /^[A-Za-z0-9_-]{21}$/;

export function isRecord(value: unknown): value is AnyRecord {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

/**
 * Replaces `id` values generated by nanoid with a fixed string.
 * Explicitly passed ids are not nanoid-shaped, so they are kept as is.
 */
export function normalizeGeneratedIds<T>(value: T): T {
  if (Array.isArray(value)) return value.map(normalizeGeneratedIds) as T;
  if (!isRecord(value)) return value;
  return Object.fromEntries(
    Object.entries(value).map(([key, item]) => [
      key,
      key === "id" && typeof item === "string" && NANOID_PATTERN.test(item)
        ? "<nanoid>"
        : normalizeGeneratedIds(item)
    ])
  ) as T;
}

/** registerOwned that assigns deterministic IDs in registration order and records each registration */
export function createOwnedRecorder(prefix = "owned") {
  const log: OwnedLog = [];
  const registerOwned: RegisterOwned = (type, data) => {
    const id = `${prefix}-${log.length}`;
    log.push({ type, id, data: normalizeGeneratedIds(data) });
    return id;
  };
  return { log, registerOwned };
}

/** Lists every leaf type string of a PayloadTemplates entry in declaration order. */
export function listTemplateTypes(template: unknown, prefix = ""): string[] {
  if (!isRecord(template)) return [];
  const result: string[] = [];
  for (const key in template) {
    if (key === "$types") continue;
    const path = prefix ? `${prefix}.${key}` : key;
    const item = template[key];
    if (isRecord(item) && item.$types === true) {
      result.push(...listTemplateTypes(item, path));
    } else {
      result.push(path);
    }
  }
  return result;
}

type Factories = typeof import("@shared/projectData/factories");

/**
 * Deterministic fixture project covering every relation kind (OWN/REF, ID/ID_ARRAY, variant case, nested).
 */
export function createRelationFixture(f: Factories): RuntimeProjectData {
  const project: RuntimeProjectData = {
    ...(f.createProject({ updatedAt: 0 } as Partial<Types.Data>) as unknown as RuntimeProjectData),
    resources: new Map(),
    variables: new Map(),
    nodes: new Map(),
    steps: new Map(),
    components: new Map(),
    elements: new Map(),
    listeners: new Map(),
    valueProcesses: new Map(),
    pluginPointers: new Map(),
    values: new Map()
  };

  let ownedIndex = 0;
  const registerOwned: RegisterOwned = (type, data) => {
    const record = data as AnyRecord;
    const normalizedId =
      typeof record.id === "string" && !NANOID_PATTERN.test(record.id)
        ? record.id
        : `${type}:owned-${ownedIndex++}`;
    if ("id" in record) record.id = normalizedId;
    (project[type] as Map<string, unknown>).set(normalizedId, data);
    return normalizedId;
  };
  const add = <K extends RecordKey>(type: K, data: AnyRecord & { id: string }) => {
    (project[type] as Map<string, unknown>).set(data.id, data);
    return data.id;
  };

  add("resources", f.createResource({ id: "res-1", src: "a.png" }));
  add("resources", f.createResource({ id: "res-2", src: "b.mp3" }));
  add("variables", f.createVariable({ id: "var-1", name: "v1" }));
  add("variables", f.createVariable({ id: "var-2", name: "v2" }));

  project.config.runtimePlugins = ["plugin-runtime-1"];
  project.pluginPointers.set("plugin-runtime-1", f.createPluginPointer(undefined, registerOwned));

  add("valueProcesses", f.createValueProcess({ id: "vp-1", type: "trim" }, registerOwned));
  add("valueProcesses", f.createValueProcess({ id: "vp-2", type: "toLowerCase" }, registerOwned));
  project.values.set("value-var", {
    baseType: "variable",
    baseValue: "var-1",
    process: ["vp-1", "vp-2"]
  } as Types.Value);
  project.values.set("value-str", { baseType: "string", baseValue: "var-2", process: [] });

  const listenerIds = [
    add(
      "listeners",
      f.createListener({ id: "lis-custom", type: "custom", output: "node-seq" }, registerOwned)
    ),
    add(
      "listeners",
      f.createListener({ id: "lis-plugin", type: "plugin", output: "node-entry" }, registerOwned)
    )
  ];

  const elementIds = [
    add("elements", f.createElement({ id: "el-empty", listeners: listenerIds }, registerOwned)),
    add(
      "elements",
      f.createElement(
        { id: "el-input", type: "input", payload: { variableId: "var-1" } } as any,
        registerOwned
      )
    ),
    add(
      "elements",
      f.createElement(
        { id: "el-adv", type: "advancedInput", payload: { variableId: "var-2" } } as any,
        registerOwned
      )
    ),
    add(
      "elements",
      f.createElement(
        { id: "el-image", type: "image", payload: { resourceId: "res-1" } } as any,
        registerOwned
      )
    ),
    add(
      "elements",
      f.createElement(
        { id: "el-video", type: "video", payload: { resourceId: "res-2" } } as any,
        registerOwned
      )
    ),
    add("elements", f.createElement({ id: "el-plugin", type: "plugin" }, registerOwned))
  ];

  add("components", f.createComponent({ id: "comp-1", elements: elementIds }, registerOwned));

  const stepIds = [
    add(
      "steps",
      f.createStep(
        { id: "step-create", type: "Component.create", payload: { componentId: "comp-1" } } as any,
        registerOwned
      )
    ),
    add(
      "steps",
      f.createStep(
        {
          id: "step-preload",
          type: "Preload.add",
          payload: { resourceArr: ["res-1", "res-2"] }
        } as any,
        registerOwned
      )
    ),
    add(
      "steps",
      f.createStep(
        { id: "step-release", type: "Preload.release", payload: { resourceArr: ["res-1"] } } as any,
        registerOwned
      )
    ),
    add(
      "steps",
      f.createStep(
        { id: "step-audio", type: "Audio.play", payload: { resourceId: "res-2" } } as any,
        registerOwned
      )
    ),
    add(
      "steps",
      f.createStep(
        { id: "step-setvar", type: "Others.setVariable", payload: { variableId: "var-2" } } as any,
        registerOwned
      )
    ),
    add("steps", f.createStep({ id: "step-plugin", type: "Others.executePlugin" }, registerOwned)),
    add("steps", f.createStep({ id: "step-delay", type: "delay" }, registerOwned))
  ];

  add(
    "nodes",
    f.createNode(
      { id: "node-entry", nodeType: "entry", output: "node-seq" } as Partial<Types.Node>,
      registerOwned
    )
  );
  add(
    "nodes",
    f.createNode(
      {
        id: "node-seq",
        nodeType: "sequence",
        steps: stepIds,
        output: "node-branch"
      } as Partial<Types.Node>,
      registerOwned
    )
  );
  add(
    "nodes",
    f.createNode(
      {
        id: "node-branch",
        nodeType: "branch",
        valueA: "value-var",
        valueB: "value-str",
        trueOutput: "node-varset",
        falseOutput: "node-entry"
      } as Partial<Types.Node>,
      registerOwned
    )
  );
  add(
    "nodes",
    f.createNode(
      {
        id: "node-varset",
        nodeType: "variableSet",
        variable: "var-1",
        output: null
      } as Partial<Types.Node>,
      registerOwned
    )
  );

  return project;
}
